package database_user

import (
	"fmt"
	"github.com/atlas-api-helper/util"
)

type Model struct {
	DeleteAfterDate *string           `json:"deleteAfterDate,omitempty"`
	AWSIAMType      *string           `json:"awsIAMType,omitempty"`
	DatabaseName    *string           `json:"databaseName,omitempty"`
	Labels          []LabelDefinition `json:"labels,omitempty"`
	LdapAuthType    *string           `json:"ldapAuthType,omitempty"`
	X509Type        *string           `json:"x509Type,omitempty"`
	Password        *string           `json:"password,omitempty"`
	ProjectId       *string           `json:"projectId,omitempty"`
	Roles           []RoleDefinition  `json:"roles,omitempty"`
	Scopes          []ScopeDefinition `json:"scopes,omitempty"`
	Username        *string           `json:"username,omitempty"`
	Profile         *string           `json:"profile,omitempty"`
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// RoleDefinition is autogenerated from the json schema
type RoleDefinition struct {
	CollectionName *string `json:"collectionName,omitempty"`
	DatabaseName   *string `json:"databaseName,omitempty"`
	RoleName       *string `json:"roleName,omitempty"`
}

// ScopeDefinition is autogenerated from the json schema
type ScopeDefinition struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

type InputModel struct {
	Username   *string `json:"username,omitempty"`
	Password   *string `json:"password,omitempty"`
	PublicKey  *string `json:"publicKey,omitempty"`
	PrivateKey *string `json:"privateKey,omitempty"`
	ProjectId  *string `json:"projectId,omitempty"`
}

func (model InputModel) String() string {
	return fmt.Sprintf(
		"Username: %s, ProjectId: %s",
		util.ToString(model.Username),
		util.ToString(model.ProjectId),
	)
}
