package database_user

import "fmt"

type Model struct {
	DeleteAfterDate   *string
	AWSIAMType        *string
	DatabaseName      *string
	Labels            []LabelDefinition
	LdapAuthType      *string
	X509Type          *string
	Password          *string
	ProjectId         *string
	Roles             []RoleDefinition
	Scopes            []ScopeDefinition
	UserCFNIdentifier *string
	Username          *string
	Profile           *string
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *string
	Value *string
}

// RoleDefinition is autogenerated from the json schema
type RoleDefinition struct {
	CollectionName *string
	DatabaseName   *string
	RoleName       *string
}

// ScopeDefinition is autogenerated from the json schema
type ScopeDefinition struct {
	Name *string
	Type *string
}

type InputModel struct {
	Username     *string
	Password     *string
	DatabaseName *string
	PublicKey    *string
	PrivateKey   *string
	ProjectId    *string
}

func (model InputModel) String() string {
	return fmt.Sprintf(
		"Username: %s, Password: %s, DatabaseName: %s, ProjectId: %s",
		toString(model.Username),
		toString(model.DatabaseName),
		toString(model.ProjectId),
	)
}

func toString(s *string) string {
	if s != nil {
		return *s
	}
	return ""
}
