package database_user

type Model struct {
	DeleteAfterDate   *string
	AWSIAMType        *string
	DatabaseName      *string
	Labels            []LabelDefinition
	LdapAuthType      *string
	X509Type          *string
	Password          *string
	ProjectId         *string
	Roles             []RoleDefinition
	Scopes            []ScopeDefinition
	UserCFNIdentifier *string
	Username          *string
	Profile           *string
}

// LabelDefinition is autogenerated from the json schema
type LabelDefinition struct {
	Key   *string
	Value *string
}

// RoleDefinition is autogenerated from the json schema
type RoleDefinition struct {
	CollectionName *string
	DatabaseName   *string
	RoleName       *string
}

// ScopeDefinition is autogenerated from the json schema
type ScopeDefinition struct {
	Name *string
	Type *string
}
