/*
MMC Atlas API Helper

Testing ClusterRestoreAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mmc_atlas_api_client

import (
	"context"
	openapiclient "github.com/mongodb/atlas-api-wrapper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_mmc_atlas_api_client_ClusterRestoreAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ClusterRestoreAPIService CreateRestoreJob", func(t *testing.T) {
		// TODO this test is incomplete. You should add your own test code here.
		t.Skip("skip test") // remove to run test

		var clusterName string
		var projectId string
		// var snapshotId string
		// var opLogTs int
		// var opLogInc int
		// var pointInTimeUtcSeconds int
		// var targetClusterName string
		// var targetProjectId string
		// var deliveryType string

		resp, httpRes, err := apiClient.ClusterRestoreAPI.CreateRestoreJob(context.Background(), clusterName, projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ClusterRestoreAPIService GetRestoreJob", func(t *testing.T) {
		// TODO this test is incomplete. You should add your own test code here.
		t.Skip("skip test") // remove to run test

		var clusterName string
		var projectId string
		// var jobId string

		resp, httpRes, err := apiClient.ClusterRestoreAPI.GetRestoreJob(context.Background(), clusterName, projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
