/*
MMC Atlas API Helper

Testing CloudBackupScheduleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mmc_atlas_api_client

import (
	"context"
	openapiclient "github.com/mongodb/atlas-api-wrapper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_mmc_atlas_api_client_CloudBackupScheduleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CloudBackupScheduleAPIService GetCloudBackupSchedule", func(t *testing.T) {
		// TODO this test is incomplete. You should add your own test code here.
		t.Skip("skip test") // remove to run test

		var projectId string
		var clusterName string

		resp, httpRes, err := apiClient.CloudBackupScheduleAPI.GetCloudBackupSchedule(context.Background(), projectId, clusterName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudBackupScheduleAPIService UpdateClusterBackupPolicy", func(t *testing.T) {
		// TODO this test is incomplete. You should add your own test code here.
		t.Skip("skip test") // remove to run test

		var projectId string
		var clusterName string
		// TODO: create model
		var updateInputModel openapiclient.CloudBackupScheduleModel = openapiclient.CloudBackupScheduleModel{}

		resp, httpRes, err := apiClient.CloudBackupScheduleAPI.UpdateClusterBackupPolicy(context.Background(), projectId, clusterName, &updateInputModel).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
